nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200', 'https://localhost:4200']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['http://localhost:4200', 'https://localhost:4200']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            expose_headers: ['Link']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
